server:
  port: 80
spring:
  datasource:
    url: jdbc:sqlserver://10.0.0.10:1433;database=willyan-webapp-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: willyan
    password: Selene@032022@1
  jpa:
    hibernate:
      ddl-auto: create